version: '3.8'

services:
  db_classificador:
    image: postgres:15-alpine
    container_name: db_classificador
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: classificador
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - net_classificador

networks:
  net_classificador:
    driver: bridge
